# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zihao/socket_labs/cerveur

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zihao/socket_labs/cerveur

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zihao/socket_labs/cerveur/CMakeFiles /home/zihao/socket_labs/cerveur//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zihao/socket_labs/cerveur/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/zihao/socket_labs/cerveur/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CerveurCore

# Build rule for target.
CerveurCore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CerveurCore
.PHONY : CerveurCore

# fast build rule for target.
CerveurCore/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CerveurCore.dir/build.make CMakeFiles/CerveurCore.dir/build
.PHONY : CerveurCore/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named spdlog

# Build rule for target.
spdlog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spdlog
.PHONY : spdlog

# fast build rule for target.
spdlog/fast:
	$(MAKE) $(MAKESILENT) -f _deps/spdlog-build/CMakeFiles/spdlog.dir/build.make _deps/spdlog-build/CMakeFiles/spdlog.dir/build
.PHONY : spdlog/fast

src/http_conn.o: src/http_conn.cc.o
.PHONY : src/http_conn.o

# target to build an object file
src/http_conn.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CerveurCore.dir/build.make CMakeFiles/CerveurCore.dir/src/http_conn.cc.o
.PHONY : src/http_conn.cc.o

src/http_conn.i: src/http_conn.cc.i
.PHONY : src/http_conn.i

# target to preprocess a source file
src/http_conn.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CerveurCore.dir/build.make CMakeFiles/CerveurCore.dir/src/http_conn.cc.i
.PHONY : src/http_conn.cc.i

src/http_conn.s: src/http_conn.cc.s
.PHONY : src/http_conn.s

# target to generate assembly for a file
src/http_conn.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CerveurCore.dir/build.make CMakeFiles/CerveurCore.dir/src/http_conn.cc.s
.PHONY : src/http_conn.cc.s

src/http_server.o: src/http_server.cc.o
.PHONY : src/http_server.o

# target to build an object file
src/http_server.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CerveurCore.dir/build.make CMakeFiles/CerveurCore.dir/src/http_server.cc.o
.PHONY : src/http_server.cc.o

src/http_server.i: src/http_server.cc.i
.PHONY : src/http_server.i

# target to preprocess a source file
src/http_server.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CerveurCore.dir/build.make CMakeFiles/CerveurCore.dir/src/http_server.cc.i
.PHONY : src/http_server.cc.i

src/http_server.s: src/http_server.cc.s
.PHONY : src/http_server.s

# target to generate assembly for a file
src/http_server.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CerveurCore.dir/build.make CMakeFiles/CerveurCore.dir/src/http_server.cc.s
.PHONY : src/http_server.cc.s

src/main.o: src/main.cc.o
.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/main.cc.s
.PHONY : src/main.cc.s

src/routes.o: src/routes.cc.o
.PHONY : src/routes.o

# target to build an object file
src/routes.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CerveurCore.dir/build.make CMakeFiles/CerveurCore.dir/src/routes.cc.o
.PHONY : src/routes.cc.o

src/routes.i: src/routes.cc.i
.PHONY : src/routes.i

# target to preprocess a source file
src/routes.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CerveurCore.dir/build.make CMakeFiles/CerveurCore.dir/src/routes.cc.i
.PHONY : src/routes.cc.i

src/routes.s: src/routes.cc.s
.PHONY : src/routes.s

# target to generate assembly for a file
src/routes.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CerveurCore.dir/build.make CMakeFiles/CerveurCore.dir/src/routes.cc.s
.PHONY : src/routes.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CerveurCore"
	@echo "... server"
	@echo "... spdlog"
	@echo "... src/http_conn.o"
	@echo "... src/http_conn.i"
	@echo "... src/http_conn.s"
	@echo "... src/http_server.o"
	@echo "... src/http_server.i"
	@echo "... src/http_server.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/routes.o"
	@echo "... src/routes.i"
	@echo "... src/routes.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/zihao/socket_labs/cerveur/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

